language: c

sudo: required

service:
  - docker

## NOTIFICATIONS
notifications:
  email:
    recipients:
    - matteo.fauchon@epitech.eu
    - lucas.fabreguettes@epitech.eu
    on_success: always
    on_failure: always

before_install:
  - docker pull epitechcontent/epitest-docker

jobs:
    include :
        - stage: build
          name: "Build"
          if: branch IN (master, develop)
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make"

        - stage: deploy
          name: "Deployement"
          if: branch = master AND type NOT IN (cron, pull_request)
          before_script:
            - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
            - git checkout master
          script:
            - git push --repo=git@git.epitech.eu:/matteo.fauchon@epitech.eu/CPE_dante_2018 --force
